refactor: add typescript [ECO-1017]
contentstack/contentstack-vuejs-starter-app pull request #27
Opened 2022-05-20 08:34 UTC by karantalapalli

refactor: add typescript [ECO-1017]

2022-05-20 09:22 UTC, surajcontentstack requested changes

2022-05-20 09:22 UTC, surajcontentstack commented on src/components/HeaderContent.vue
>            const hFound = response[0].navigation_menu.find(
use `navHeaderList` variable

2022-05-20 09:22 UTC, surajcontentstack commented on src/views/BlogContent.vue
> +    author: [];
type can be `Array<any>`

2022-05-20 09:22 UTC, surajcontentstack commented on src/views/BlogContent.vue
> +      const archived = [] as any;
as `Array<any>`

2022-05-20 09:22 UTC, surajcontentstack commented on src/views/BlogContent.vue
> +      const element: any = document.getElementsByClassName('cslp-tooltip');
check if you can use `this$refs` to access DOM elements

2022-05-20 11:42 UTC, abhishek305 reviewed
use models instead of interfaces wherever applicable @karantalapalli

2022-05-20 11:42 UTC, abhishek305 commented on src/components/AboutSectionBucket.vue
> +}
For individual components have a common file from were you export **interface** using models
reference: https://dev.to/jwp/typescript-models-and-javascript-objects-31b3

2022-05-20 11:42 UTC, abhishek305 commented on src/components/BlogSection.vue
> +}
For individual components have a common file from were you export interface using models.

2022-05-20 11:42 UTC, abhishek305 commented on src/components/Devtools.vue
> +
use models as required

2022-05-20 11:42 UTC, abhishek305 commented on src/components/FooterContent.vue
> +
use models

2022-05-23 05:00 UTC, surajcontentstack approved these changes

2022-05-24 11:16 UTC, abhishek305 approved these changes

2022-06-02 06:34 UTC, merged